### ISSUE TITLE
No module named 'cvpce.cli'

### ISSUE THREAD

**Issue by alexHxun** [laitalaj/cvpce#3]
I get error when i run the command 'cvpce --help'

**Comment by laitalaj** [comment]
Hey @alexHxun ! Did you create&activate a Conda environment as instructed in [the README](https://github.com/laitalaj/cvpce#installation)? Could you copy-paste the output of
```
conda env export
```
here?

**Comment by alexHxun** [comment]
> Hey @alexHxun ! Did you create&activate a Conda environment as instructed in [the README](https://github.com/laitalaj/cvpce#installation)? Could you copy-paste the output of
> 
> ```
> conda env export
> ```
> 
> here?

here is my output:
name: cvpce
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py38h06a4308_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - pytorch=1.8.1=py3.8_cuda11.1_cudnn8.0.5_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.9.1=py38_cu111
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - aiosignal==1.2.0
    - attrs==21.4.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cvpce==1.0.0
    - cycler==0.11.0
    - distlib==0.3.4
    - filelock==3.7.1
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - grpcio==1.43.0
    - idna==3.3
    - imageio==2.19.3
    - importlib-resources==5.7.1
    - jsonschema==4.6.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.2
    - msgpack==1.0.4
    - networkx==2.8.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.4.2
    - platformdirs==2.5.2
    - protobuf==3.20.1
    - pycocotools==2.0.4
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - ray==1.12.1
    - requests==2.28.0
    - scikit-image==0.19.2
    - scipy==1.8.1
    - squarify==0.4.3
    - tabulate==0.8.9
    - tensorboardx==2.5.1
    - tifffile==2022.5.4
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - zipp==3.8.0
prefix: /home/ubuntu/miniconda3/envs/cvpce
'

Thank you for your reply!

**Comment by alexHxun** [comment]
I'm very glad you took the time to solve my problem ,  I just read your paper these two days, nice work! I am not very clear about one point:  Before you built the graph for observed image , have you get the label of per product in the observed image?  In the other words, do you detect category of each product when you do  object detection? or you just get the bounding boxes of each product? 

I'd appreciate it if you could respond

**Comment by alexHxun** [comment]
> I'm very glad you took the time to solve my problem , I wanna ask another question if you don`t mind. I just read your paper these two days, nice work! I am not very clear about one point: Before you built the graph for observed image , have you get the label of per product in the observed image? In the other words, do you detect category of each product when you do object detection? or you just get the bounding boxes of each product?
> 
> I'd appreciate it if you could respond

**Comment by alexHxun** [comment]
> > I'm very glad you took the time to solve my problem , I wanna ask an another question if you don`t mind it . I just read your paper these two days, nice work! I am not very clear about one point: Before you built the graph for observed image , have you get the label of per product in the observed image? In the other words, do you detect category of each product when you do object detection? or you just get the bounding boxes of each product?
> > I'd appreciate it if you could respond

**Comment by alexHxun** [comment]
Error:
`Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/cvpce/bin/cvpce", line 5, in <module>
    from cvpce.cli import cli
ModuleNotFoundError: No module named 'cvpce.cli'
`
Maybe my path is incorrect?

**Comment by Sajad-Hosseini** [comment]
Hi. I also get the same error. Is this issue resolved?
`Traceback (most recent call last):
  File "/usr/local/bin/cvpce", line 5, in <module>
    from cvpce.cli import cli
ModuleNotFoundError: No module named 'cvpce.cli'`
@alexHxun @laitalaj

**Comment by laitalaj** [comment]
Sorry about the late reply! And especially sorry to @alexHxun for the almost 2 year delay 😅  I completely missed your responses!

Hmm, I might know what could be causing this. @Sajad-Hosseini , does this work if you run the command in the repository root?

A bit of context: Looks like I used relative imports back in 2021. Switching to absolute imports might fix this. I'll see if I'd have time to do that at some point 🤔

**Comment by Sajad-Hosseini** [comment]
Hello again!
No, it doesn't :(
That would be great if you could release an update.
